#https://developers.cloudflare.com/workers/wrangler/configuration/#keys
name = "ip-api-pkgforge"
main = "./index.js"
#https://developers.cloudflare.com/workers/configuration/compatibility-dates/
compatibility_date = "2024-05-13"
workers_dev = false
logpush = true
routes = [
    { pattern = "ip.pkgforge.dev/*", zone_name = "pkgforge.dev" }
]

# D1 Database for visitor logs
[[d1_databases]]
binding = "DB"
database_name = "visitor_logs"
database_id = "visitor_logs"