#https://developers.cloudflare.com/workers/wrangler/configuration/#keys
name = "opaz"
main = "./index.js"
#https://developers.cloudflare.com/workers/configuration/compatibility-dates/
compatibility_date = "2024-12-01"
workers_dev = false

# D1 Database for visitor logs
[[d1_databases]]
binding = "DB"
database_name = "visitor_logs"
database_id = "376db482-f36a-4193-8c48-ab6a7a8990b8"
